<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PlanetSimulator.Rendering/PlanetSimulator.Rendering.csproj" />
    <ProjectReference Include="../PlanetSimulator.Simulation/PlanetSimulator.Simulation.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12" PrivateAssets="all" />
  </ItemGroup>
</Project>
